# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load bundler integration (runs bundle install on deploy)
require "capistrano/bundler"

# Load Rails-specific tasks (assets, migrations)
require "capistrano/rails/assets"
require "capistrano/rails/migrations"

# Load custom tasks from `lib/capistrano/tasks` if you define them.
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
