source "https://rubygems.org"

gem "rails"
gem "propshaft"
gem "sqlite3"
gem "puma"
gem "rack-cors"
gem "bootsnap", require: false
gem "image_processing"
gem "solid_queue"
gem "capistrano", "~> 3.19", require: false
gem "capistrano-rails", "~> 1.6", require: false
gem "capistrano-bundler", "~> 2.1", require: false
gem "sentry-ruby", "~> 5.22"
gem "sentry-rails", "~> 5.22"

group :development, :test do
  gem "debug", platforms: %i[ mri ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "webmock"
end
