source "https://rubygems.org"

gem "rails", "~> 8.1.2", ">= 8.1.2.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "bootsnap", require: false
gem "capistrano", "~> 3.19", require: false
gem "capistrano-rails", "~> 1.6", require: false
gem "capistrano-bundler", "~> 2.1", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mswin ], require: "debug/prelude"
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "webmock"
end
